name: Test Actions

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test basic functionality
        run: |
          echo "GitHub Actions is working!"
          echo "Current branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          
      - name: List tags
        run: |
          git fetch --tags
          echo "Available tags:"
          git tag -l